spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 985878687237-cicutlukd65ppl03l9cr1itf38fs66t4.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: VdrgQTkuTzW0ZzQ4KRf8
            client-secret: FrehdkhQpq
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 085f5cf081930f9a65d2724d19cae378
            client-secret: IHCJBrVFDrjEz0HtsHKgUcABhQXqYb56
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id